# Generated by Django 4.1.5 on 2023-02-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_log', '0003_rename_big_park_distance_score_house_distance_to_park_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bus_commute_gym',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='bus_commute_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='car_commute_gym',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='car_commute_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='walk_commute_gym',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='walk_commute_work',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User_Commute',
        ),
    ]
