# Generated by Django 4.1.5 on 2023-02-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_log', '0006_alter_house_bus_commute_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='walk_dist_commute_gym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='walk_dist_commute_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
