# Generated by Django 4.1.5 on 2023-02-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_log', '0007_alter_house_walk_dist_commute_gym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
