# Generated by Django 4.1.5 on 2023-03-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_log', '0008_house_latitude_house_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='outdoor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
